spring.datasource.url=jdbc:postgresql://localhost:5435/fast_cart_db
spring.datasource.username=fast_cart_user
spring.datasource.password=fast_cart_123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=hDoTKzw65Fknid6gTVWH4n3YKrm79xisQI0CqQX+IjB7yuzRldz2ThuBwP2eV4VG
security.jwt.access-token-expiration-ms=900000
security.jwt.refresh-token-expiration-ms=604800000