spring.datasource.url=jdbc:postgresql://localhost:5435/fast_cart_db
spring.datasource.username=fast_cart_user
spring.datasource.password=fast_cart_123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true